version: '2'
services:
  publish:
    build: ./aem-publish
    image: aem-publish:aem-p
    ports:
      - "4503:4503"
      - "8003:8000"
      
  author:
    build: ./aem-author
    image: aem-author:aem-a
    ports:
      - "4502:4502"
      - "8802:8000"
      

  dispatcher:
    build: ./aem-dispatcher
    image: aem-dispatcher:aem-disp
    ports:
      - "80:80"
    
